version: '3'
services:
  web:
    build:
      context: ./docker/php
      args:
        user_id: 1000
    image: wedevelopcoffee/php-74-apache
    container_name: php
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    volumes:
      - "./public:/var/www/html"
  mysql:
    build:
      context: ./docker/mysql
      args:
        user_id: ${USER_ID}
    image: mrkoopie/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - "./mysql_data:/var/lib/mysql"